root: ./

structure:
  readme: ./README.md
  summary: ./SUMMARY.md

redirects:
  node/advanced-increase-spending-balance-with-on-chain-bitcoin: node/advanced-increase-lightning-balance-with-on-chain-bitcoin.md
